blog/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView #, AddPostView, UpdatePostView, DeletePostView #category_list ,  #CatListView #post_create, post_update ,
from .import views

app_name = 'blog'

urlpatterns = [
    #path('', views.post_list,name='post-list'),
    #path('<slug:category_slug>', views.home,name='post_by_category'),
    #path('category/<slug:category_slug>/>', views.category_list, name='post_by_category'),
    #path('<int:pk>/', views.article_detail, name='article-detail'),
    path('', HomeView.as_view(),name='post-list'),
    #path('category/<slug:slug>/', views.category_list, name='category'),
    #path('category/<slug:slug>/',views.category,name='category'),
    path('article/<int:pk>', ArticleDetailView.as_view(),name='article-detail'),
    path('newsletter/', views.newsletter_signup,name='newsletter'),
    #path('category/<category>', CatListView.as_view(),name='category'),
    #path('create/', AddPostView.as_view(),name='post-create'),
    #path('article/<int:pk>/edit/', UpdatePostView.as_view(),name='update-post'),
    #path('article/<int:pk>/remove/', DeletePostView.as_view(),name='delete-post'),
    path('create/', views.post_create, name='post-create'),
    path('article/<int:pk>/update/', views.post_update, name='post-update'),
    path('article/<int:pk>/delete/', views.post_delete, name='post-delete'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from users.views import profile, login, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', about,name='about'),
    path('accounts/profile/', profile,name='profile'),
    path('account/login/', login,name='login'),
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

templates/category/post_by_category.html
{% extends 'blog/base.html' %}
{% load static %}


{% block content %}

<!--? Blog Area Start -->
<section class="home-blog-area section-padding30">
    <div class="container">
        <!-- Section Tittle -->
        <div class="row justify-content-center">
            <div class="col-lg-7 col-md-9 col-sm-10">
                <div class="section-tittle text-center mb-100">
                    <h2>{{category.title}}</h2>
                    <p>Discover The most recent Products </p>
                </div>
            </div>
        </div>
        <div class="row">
            {% for post in posts %}
            <div class="col-lg-4 col-md-6">
                <div class="home-blog-single mb-40">
            
                   
                    <a href="{{post.category.get_absolute_url}}"><h4 class="text-muted">{{post.category}}</h4></a>
                   
                
                    <div class="blog-img-cap">
                        <div class="blog-img">
                            <img src="{{post.image.url}}" alt="">
                        </div>
                        <div class="blog-cap">
                            <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
                            <P>{{post.overview}}.</P>
                        </div>
                        <a href="{% url 'blog:article-detail' post.pk %}" class="btn" data-animation="fadeInLeft" data-delay=".3s">Read More...</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<nav class="blog-pagination justify-content-center d-flex">
    <ul class="pagination">
        <li class="page-item">
            <a href="#" class="page-link" aria-label="Previous">
                <i class="ti-angle-left"></i>
            </a>
        </li>
        <li class="page-item">
            <a href="#" class="page-link">1</a>
        </li>
        <li class="page-item active">
            <a href="#" class="page-link">2</a>
        </li>
        <li class="page-item">
            <a href="#" class="page-link" aria-label="Next">
                <i class="ti-angle-right"></i>
            </a>
        </li>
    </ul>
</nav>

     <!--Pagination-->
  {% if is_paginated %}
  <nav class="d-flex justify-content-center wow fadeIn">
    <ul class="pagination pg-blue">

      <!--Arrow left-->
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
       {% endif %}
      <li class="page-item active">
        <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
          <span class="sr-only">(current)</span>
        </a>
      </li>
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
  <!--Pagination-->
<!-- Blog Area End -->
<!--? About Law Start-->
<!--section class="about-low-area mt-30">
    <div class="container">
        <div class="about-cap-wrapper">
            <div class="row">
                <div class="col-xl-5  col-lg-6 col-md-10 offset-xl-1">
                    <div class="about-caption mb-50">
                        <!-- Section Tittle ->
                        <div class="section-tittle mb-35">
                            <h2>100% satisfaction guaranteed.</h2>
                        </div>
                        <p>Almost before we knew it, we had left the ground</p>
                        <a href="about.html" class="border-btn">Make an Appointment</a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <!-- about-img ->
                    <div class="about-img">
                        <div class="about-font-img">
                            <img src="{% static 'assets/img/gallery/about2.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section-->
<!-- About Law End-->

<style type="text/css">
  .section-tittle{
    margin-top: -60;
  }
  .row{
    margin-top: -10px;
  }
  .home-blog-single{
    background-color: #fff;
    padding: 10px;
    border-radius: 8px;
  }
  .blog-img{
    width: 270px;
    border-radius: 1px ! important;
  }
</style>

{% endblock content %}