blog/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView #, AddPostView, UpdatePostView, DeletePostView #category_list ,  #CatListView #post_create, post_update ,
from .import views

app_name = 'blog'

urlpatterns = [
    #path('', views.post_list,name='post-list'),
    #path('<slug:category_slug>', views.home,name='post_by_category'),
    #path('category/<slug:category_slug>/>', views.category_list, name='post_by_category'),
    #path('<int:pk>/', views.article_detail, name='article-detail'),
    path('', HomeView.as_view(),name='post-list'),
    #path('category/<slug:slug>/', views.category_list, name='category'),
    #path('category/<slug:slug>/',views.category,name='category'),
    path('article/<int:pk>', ArticleDetailView.as_view(),name='article-detail'),
    path('newsletter/', views.newsletter_signup,name='newsletter'),
    #path('category/<category>', CatListView.as_view(),name='category'),
    #path('create/', AddPostView.as_view(),name='post-create'),
    #path('article/<int:pk>/edit/', UpdatePostView.as_view(),name='update-post'),
    #path('article/<int:pk>/remove/', DeletePostView.as_view(),name='delete-post'),
    path('create/', views.post_create, name='post-create'),
    path('article/<int:pk>/update/', views.post_update, name='post-update'),
    path('article/<int:pk>/delete/', views.post_delete, name='post-delete'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from users.views import profile, login, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', about,name='about'),
    path('accounts/profile/', profile,name='profile'),
    path('account/login/', login,name='login'),
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Category(models.Model):
	title = models.CharField(max_length=200,db_index=True)
	slug = models.SlugField(max_length=200,db_index=True, unique=True)

	class Meta:
		ordering = ('-title',)
		verbose_name = 'Category'
		verbose_name_plural = 'Categories'

	def __str__(self):
		return self.title

def get_absolute_url(self):
        return reverse('blog:category', args=[self.slug])

class Post(models.Model):
    category=models.ForeignKey(Category,related_name="posts", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    overview = models.TextField(blank=True, null=True)
    content = RichTextUploadingField(blank=True, null=True)
    image = models.ImageField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-title',)
	

def get_absolute_url(self):
	return reverse('blog:post-list')

def get_absolute_url(sself):
	return reverse('blog:article-detail',kwargs={
		'pk': self.pk
		})

blog/forms.py

from django.forms import ModelForm
from .models import Post, Category
from django import forms
from users.models import Signup

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        #field = ('title', 'overview', 'image')

class EmailSignupForm(forms.ModelForm):

    class Meta:
        model = Signup
        fields = ['email', ]
        def clean_email(self):
            email = self.cleaned_data.get('email')
            return email

blog/views.py

from django.shortcuts import render, redirect,reverse, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from .models import Post , Category
from .forms import PostForm
from users.models import Signup
from .forms import EmailSignupForm
from django.urls import reverse_lazy
from django.contrib import messages



 #Create your views here.
"""
def get_category_count():
	queryset = Post.objects.values('category__title').annotate(Count('category__title'))
	return queryset

def home(request, category_slug = None):
	category = None
	categories = Category.objects.all()
	posts = Post.objects.all()
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		posts =post.filter(category = category)
	context ={
	   'categories': categories,
	   'category': category,
	   'posts': posts

	}
	return render(request,'blog/home.html',context)
"""
"""
def post_list(request,category_slug=None):
    queryset = Post.objects.all()
    category_count = get_category_count()
    paginator = Paginator(queryset, 3)
    page_request_var = 'page'
    page =request.GET.get(page_request_var)
    try:
    	paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
    	paginated_queryset = paginator.page(1)
    except EmptyPage:
    	paginated_queryset = paginator.page(paginator.num_pages)
	

    context ={
       #'queryset':posts,
		'queryset':paginated_queryset,
		'page_request_var':page_request_var,
		#'most_recent':most_recent,
		'category_count':category_count
    }

    return render(request, 'blog/home.html', context) 

def article_detail(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if request.method == "POST":
	    email = request.POST["email"]

	    ew_signup = Signup()
	    ew_signup.email = email
	    ew_signup.save()
	    
    return render(request,'blog/article.html',{'post':post})

def category(request, slug):
	category = Category.objects.get(slug=slug)

	context={
	   'category':category
	}
	return renser(request, 'blog/category.html', context)


class AddPostView(LoginRequiredMixin, CreateView):
	model = Post
	form_class = PostForm
	#field = ('title', 'overview', 'image')
	template_name = 'blog/post_create.html'

class UpdatePostView(LoginRequiredMixin, UpdateView):
	model = Post
	template_name = 'blog/update.html'
	fields ='__all__'
	#fields = ['title','overview','image']

class DeletePostView(LoginRequiredMixin,DeleteView):
	model = Post
	template_name = 'blog/delete.html'
	success_url = reverse_lazy('blog:post-list')



def category_list(request, category_slug, slug):
	categories =Category.objects.all()
	post = Post.objects.filter(category=category)
	if category_slug:
		category =get_object_or_404(Category, slug=category_slug)
		post = post.filter(category=category)

	context={
	   'categories':categories,
	   'category': category,
	   'post':post,
	}
	return render(request, 'category/post_by_category.html',context)

def article_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)

	context={
	   'post': post
	}
	return render(request, 'blog/article.html', context)


"""
class HomeView(ListView):
	model =  Post
	paginate_by = 3
	template_name = 'blog/home.html'
	ordering = ['-id']

class ArticleDetailView(DetailView):
	model = Post
	def post(request):
		post=get_object_or_404(Post,pk=pk)	
		form = EmailSignupForm(request.POST or None)
		if form.is_valid():
			instance=form.save(commit=False)
			if Signup.objects.filter(email=instance.email).exists():
				messages.warning(request,"Sorry! your email already exists!")
			else:
				instance.save()
				messages.success(request,"Thank You For Subscribing!")
				return redirect('users:about')
		
	template_name = 'blog/article.html'

def newsletter_signup(request):
	form = EmailSignupForm(request.POST or None)
	if form.is_valid():
		instance=form.save(commit=False)
		if Signup.objects.filter(email=instance.email).exists():
			messages.warning(request,"Sorry! your email already exists!")
		else:
			instance.save()
			messages.success(request,"Thank You For Subscribing!")
			return redirect('users:about')

	context={
	  'form': form
	}
	return render(request,'accounts/newsletter_signup.html',context)




"""
class AddPostView(LoginRequiredMixin, CreateView):
	model = Post
	form_class = PostForm
	#field = ('title', 'overview', 'image')
	template_name = 'blog/post_create.html'

class UpdatePostView(LoginRequiredMixin, UpdateView):
	model = Post
	template_name = 'blog/update.html'
	fields ='__all__'
	#fields = ['title','overview','image']

class DeletePostView(LoginRequiredMixin,DeleteView):
	model = Post
	template_name = 'blog/delete.html'
	success_url = reverse_lazy('blog:post-list')


def CategoryView(request, slug):
	category = get_object_or_404(Category, slug=slug)
	posts = category.posts.all()

	context={
	    'category':category,
	    'posts': posts
	}
	return render(request, 'blog/category.html',context)

def category_list(request, slug):
	category =Category.objects.get(slug=slug)

	context={
	   'category': category
	}
	return render(request, 'blog/category.html',context)


class CatListView(ListView):
	model= Post
	template_name ='blog/category.html'

	def get_queryset(self):
		category = self.get_object_or_404(Category, pk=self.kwargs['pk'])
		return Post.objects.filter(category=self.category)

	def get_context_data(self, **kwargs):
		context = super(CatListView, self).get_context_data(**kwargs)
		context['category'] =self.category
		return context

def PostCategory(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	post = Post.objects.all()
	if category_slug:
		category = get_object_or_404(Category,slug=category_slug)
		post = Post.filter(category=category)
	context ={
	 'categories': categories,
	 'post': post,
	 'category': category
	}
	return render(request, 'blog/category.html', context)
"""



@login_required
def post_create(request):
	form = PostForm()
	if request.method== "POST":
		form = PostForm(request.POST or None, request.FILES or None)
		if form.is_valid():
		   form.save()
		return redirect('blog:post-list')
	context ={
	'form':form
	}
	return render(request,'blog/post_create.html',context)

@login_required
def post_update(request, pk):
	post =Post.objects.get(id=pk)
	form = PostForm(instance=post)
	if request.method== "POST":
		form = PostForm(request.POST, instance=post) #or None, request.FILES or None)
		if form.is_valid():
		   form.save()
		return redirect('blog:post-list')
	context ={
	'form':form
	}
	return render(request,'blog/post_create.html',context)

@login_required
def post_delete(request, pk):
	post =Post.objects.get(id=pk)
	#form = PostForm(instance=post)
	if request.method== "POST":
		post.delete()
		#form = PostForm(request.POST, instance=post)
		#if form.is_valid():
		   #form.save()
		return redirect('blog:post-list')
	context ={
	'post':post
	}
	return render(request,'blog/delete.html',context)


templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
	
	<title>Dona Marketing Site</title>
	{% include 'blog/head.html' %}
</head>
<body>
	
	{% include 'blog/nav.html' %}

	{% include 'blog/header.html' %}

	{% if messages %}
    <div>
      <!---strong>Messages:</strong--->
      <ul>
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
			<li>{{message}}</li>
			<button type="close" class="close" data-dismiss="alert" aria-label="close">
			<span aria-hidden="true">&times;</span>
				
			</button>
		</div>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    {% block content %}{% endblock content %}

    {% include 'blog/footer.html' %}
    {% include 'blog/scripts.html' %}
</body>
</html>

<style type="text/css">
	body{
		background-color: #f4f4f4;
	}
	.alert{
      font-size: 20px;
      text-align: center;
	}
</style>

templates/blog/delete.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %} Delete Post {% endblock title %}
{% block content %}
<br>
<div class="container">
	<div class="row-d">
		<div class="col-5 offset-4">
			<h4 class="del">Delete:{{post.title}}!</h4>
			<hr>
			<br>
			<form class="form-d" action="." method="POST" enctype="multipart/form-data">
				{% csrf_token %}

			<strong><h5 class="warning">Are you sure, you want to delete it?</h5></strong>
				<!--input type="submit"class="btn btn-outline-info-danger" name="Delete"-->
				<br>
				<hr>
				<br>
			    <button class="btn btn-danger btn-block"><h5>Delete</h5></button>
			</form>
		</div>
	</div>
</div>
<br>

<style type="text/css">
	.warning{
		color: green;
		text-align: center;
	}
	.row-d{
		background-color: #fff;
		padding: 10px;
		/*--border-radius: 5px;--*/
		/*--box-shadow: 0px 0px 10px 0px #000;--*/
	}
	.del{
		background-color: grey;
		padding: 3px;
		text-align: center;
		color: #fff;
	}
</style>
{% endblock content %}

templates/blog/footer.html
{% load static %}

 <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->

    <hr class="my-4">

    <!-- Social icons -->

    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      <p>
      © 2020 Copyright:
      <a href="https://www.sridona.com" target="_blank"> Dona Marketing </a>
     </p>
    </div>
    <!--/.Copyright-->
    <div class="disclaim">
    <h4>Disclosure:</h4> This is a professional review blog which gets compensated for the products reviewed by the companies who produce them. All of the products are tested thoroughly and high grades are received only by the best ones. I am an independent blogger and the reviews are done based on my own opinions. Bear in mind that some of the links in this post are affiliate links and if you go through them to make a purchase I will earn a commission. I link these companies and their products because of their quality and not because of the commission I receive from your purchases, by the end the decision is yours, and whether or not you decided to buy something is completely up to you.I hope you enjoy our products as much as we enjoy offering them to you.Thank you for your visit.
    </div>
  </footer>

  <style type="text/css">
    .page-footer{
      background-color: #D8D8D8;
    }
    .disclaim{
    	margin-top: -15px;
    	margin-bottom: 15px;
    	padding: 15px;
    }
  </style>

templates/blog/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
   
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/dona6.png' %}" width="400">
    <!--ckeditor---->
    <script src="https://cdn.ckeditor.com/4.15.0/full/ckeditor.js"></script>
    <script src="https://cdn.ckeditor.com/[version.number]/[distribution]/ckeditor.js"></script>

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated-headline.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

    <script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/a39d54314f0282ee2369a8b63/8be9bb7bd84694ffe3a7279d5.js");</script>
</head>

templates/blog/header.html
{% load static %}

  <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'img/dona6.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!--? Header Start -->
        <div class="header-area">
            <div class="main-header header-sticky">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-2 col-lg-2 col-md-1">
                            <div class="logo">
                            	<!--a href="{% url 'blog:post-list' %}" class="my-logo"><h2>DONA</h2></a-->
                                <a href="{% url 'blog:post-list' %}"><img src="{% static 'img/dona4.png' %}" class="my-logo" alt=""-></a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10 col-md-10">
                            <div class="menu-main d-flex align-items-center justify-content-end">
                                <!-- Main-menu -->
                                <div class="main-menu f-right d-none d-lg-block">
                                    <nav> 
                                        <ul id="navigation">
                                            <li><a href="{% url 'blog:post-list' %}">Home</a></li>
                                            <li><a href="{% url 'about' %}">About</a></li>
                                            {% if user.is_staff %}
                                            <li><a href="{% url 'blog:post-create' %}">Add Post</a></li>
                                             <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
                                            {% endif %}
                                            <!--li><a href="blog.html">Blog</a>
                                                <ul class="submenu">
                                                    <li><a href="blog.html">Blog</a></li>
                                                    <li><a href="blog_details.html">Blog Details</a></li>
                                                    <li><a href="elements.html">Element</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="contact.html">Contact</a></li>
                                        </ul-->
                                    </nav>
                                </div>
                             
                                <div class="header-right-btn f-right d-none d-lg-block ml-15">
                                    <a href="{% url 'account_login' %}" class="btn btn-sm btn-success">Log In</a>
                                </div>
                             
                            </div>
                        </div>   
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>

     <!--? Slider Area Start-->
        <!--div class="slider-area"-->
            <!--div class="slider-active dot-style"-->
    <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'img/lemon-water1.jpg' %}"width="1200;" height="400;" width="1200;" height="400;"  alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h1 class="header-text">HEALTH IS WEALTH </h1>
            <!--p>dgfdhghmh</p-->
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/study1.jpg' %}"width="1200;" height="400;" width="1200;" height="400;" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h1 class="header-text">EASY LEARNING </h1>
            <!--p>kljfkhgsdeg</p-->
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/money.png' %}"width="1200;" height="400;" width="1200;" height="400;" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h1 class="header-text">ONLINE BUSINESS </h1>
            <!--p>Hi There</p-->
          </div>
        </div>
        <!--div class="carousel-item">
          <img class="d-block w-100" src="{% static 'img/money.png' %}" alt="Second slide">
          <h1 class="header-text">ONLINE BUSINESS</h1>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'img/study1.jpg' %}" alt="Third slide">
          <h1 class="header-text">EASY LEARNING</h1>
        </div-->
      </div>
      <!--a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a-->
    </div>            


    <!--/div-->
<!--/div-->

<!-- Slider Area End -->

<style type="text/css">
    .slider-active{

    }
	.carousel-inner{

		
	}
  .carousel-item{
    width: 60%;
    height: 300px;
  }
	.hero__caption{
		margin-top: -300px;
	}
  .btn{
    padding: 15px;
  }
  .header-text{
    /*font-size: 1em = 12pt = 16px = 100%;*/
    /*margin-bottom:30px;*/
  
  }
    h1 {
  font-size: 45px;
  background: -webkit-linear-gradient(#eee, #333);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
.carousel-indicators{
  margin-top: -40px;
}
.carousel-indicators{
  transition: .5s;
}
  /*
	 .my-logo{
      float: left;
     
      background: -webkit-linear-gradient(#f4ff, #DF01D7);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent; 
      margin-left: 20px;
      margin-top: px;
      font-size: 24px;
      border-radius: 3px;
    }
  */
  .my-logo{
    width: 200px;
  }
</style>

templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}


{% block content %}

<!--? Blog Area Start -->
<section class="home-blog-area section-padding30">
    <div class="container">
        <!-- Section Tittle -->
        <div class="row justify-content-center">
            <div class="col-lg-7 col-md-9 col-sm-10">
                <div class="section-tittle text-center mb-100">
                    <h2>Our Latest Reviews 2020</h2>
                    <p>Discover The most recent Products </p>
                </div>
            </div>
        </div>
        <div class="row">
            {% for post in object_list %}
            <div class="col-lg-4 col-md-6">
                <div class="home-blog-single mb-40">
            
                   {% for cat in post.categories.all %}
                    <a href="{{post.category.get_absolute_url}}"><h4 class="text-muted">{{cat}}</h4></a>
                   
                   {% endfor %}
                    <div class="blog-img-cap">
                        <div class="blog-img">
                            <img src="{{post.image.url}}" alt="">
                        </div>
                        <p class="post-meta text-muted">Posted:
                            on {{ post.created|date:"M d, Y" }}</p>
                        <div class="blog-cap">
                            <h3><a href="{% url 'blog:article-detail' post.pk %}">{{post.title}}</a></h3>
                            <P>{{post.overview}}.</P>
                        </div>
                        <a href="{% url 'blog:article-detail' post.pk %}" class="btn" data-animation="fadeInLeft" data-delay=".3s">Read More...</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% if is_paginated %}
    <nav class="blog-pagination justify-content-center d-flex">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?page={{page_obj.previous_page_number}}" class="page-link" aria-label="Previous">
                <i class="ti-angle-left"></i>
            </a>
        </li>
        {% endif %}
        <li class="page-item active">
            <a href="?page={{page_obj.number}}" class="page-link">{{page_obj.number}}</a>
        </li>
         {% if page_obj.has_next %}
        <li class="page-item">
            <a href="?page={{page_obj.next_page_number}}" class="page-link" aria-label="Next">
                <i class="ti-angle-right"></i>
            </a>
        </li>
        {% endif %}
    </ul>
  </nav>
  {% endif %}

   <!--div class="Subscribe">
    <a href="{% url 'blog:newsletter' %}" class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
  type="submit">Subscribe Newsletter </a>
  </div-->
</section>


<!--{if queryset.has_previous }-->
<!--nav class="blog-pagination justify-content-center d-flex">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?{{page_request_var}}={{queryset.previous_page_number}}" class="page-link" aria-label="Previous">
                <i class="ti-angle-left"></i>
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a href="#" class="page-link">1</a>
        </li>
        <li class="page-item active">
            <a href="?{{page_request_var}}={{queryset.number}}" class="page-link">{{queryset.number}}</a>
        </li>
        {% if queryset.has_next %}
        <li class="page-item">
            <a href="?{{page_request_var}}={{queryset.next_page_number}}" class="page-link" aria-label="Next">
                <i class="ti-angle-right"></i>
            </a>
        </li>
        {% endif %}
    </ul>
</nav-->
<!--{ endif }-->

  
  <!--Pagination-->
<!-- Blog Area End -->
<!--? About Law Start-->
<!--section class="about-low-area mt-30">
    <div class="container">
        <div class="about-cap-wrapper">
            <div class="row">
                <div class="col-xl-5  col-lg-6 col-md-10 offset-xl-1">
                    <div class="about-caption mb-50">
                        <!-- Section Tittle ->
                        <div class="section-tittle mb-35">
                            <h2>100% satisfaction guaranteed.</h2>
                        </div>
                        <p>Almost before we knew it, we had left the ground</p>
                        <a href="about.html" class="border-btn">Make an Appointment</a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <!-- about-img ->
                    <div class="about-img">
                        <div class="about-font-img">
                            <img src="{% static 'assets/img/gallery/about2.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section-->
<!-- About Law End-->

<style type="text/css">
  .section-tittle{
    margin-top: -60;
  }
  .row{
    margin-top: -10px;
  }
  .home-blog-single{
    background-color: #fff;
    padding: 10px;
    border-radius: 8px;

  }
  .blog-img{
    width: 270px;
    border-radius: 1px ! important;
  }
  .post-meta{
    text-align: center;
    font-size: 12px;
    font-family: 'coutgete';
  }

</style>

{% endblock content %}

templates/blog/post_create.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block title %} Create Post {% endblock title %}
{% block content %}
<br>
<div class="container">
	<h4 class="title-p">Add New Post</h4>
	<div class="row justify-content-center">
	<form action="." method="POST" enctype="multipart/form-data">
	  <div class="form-group">
	   {% csrf_token %}
	   {{form.media}}
	   {{form|crispy}}

	  <button type="submit" class="btn btn-primary btn-block"><h4>Post</h4></button>
	</form>
	</div>
</div>
<br>
<style type="text/css">

	.title-p{
		background-color: grey;
		max-width: 90%;
		margin-left: 45px;
		color: #fff;
		padding: 5px;
		text-align: center;
	}
</style>


{% endblock content %}

templates/blog/update.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block title %} Update Post {% endblock title %}
{% block content %}
<br>
<div class="container">
	<h4 class="title-u">Update Post</h4>
	<div class="row justify-content-center">
	<form action="." method="POST" enctype="multipart/form-data">
	  <div class="form-group">
	   {% csrf_token %}
	   {{form.media}}
	   {{form|crispy}}

	  <button type="submit" class="btn btn-primary btn-block"><h5>Update</h5></button>
	</form>
	</div>
</div>
<br>
<style type="text/css">
	
	.title-u{
		background-color: grey;
		max-width: 90%;
		margin-left: 45px;
		color: #fff;
		padding: 5px;
		text-align: center;
	}
</style>


{% endblock content %}